/*
 * BigViewFrame.java
 *
 * Created on 13. Juni 2007, 11:42
 */

package my.CellMorphs;

import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import my.CellMorphs.*;
/**
 *
 * @author  Adrian Imfeld
 */
public class BigViewFrame extends javax.swing.JFrame {
    
    private int RenderType = CCellMorph.RTState;
    
    private CCellMorph CellMorph;
    private Timer timer;
    
    private ActionListener taskPerformer = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            CellMorph.Step();
            Draw();
        }
    };
    
    /** Creates new form BigViewFrame */
    public BigViewFrame(CGenome Genes, int aRenderType) {
        initComponents();
        RenderType = aRenderType;        
        CellMorph = new CCellMorph(CMCanvas.getWidth(), CMCanvas.getHeight(), Genes);
        timer = new Timer(0, taskPerformer);
        jButtonRunActionPerformed(null);
        
        UpdateControls();
    }
    
    private void Draw() {
        CellMorph.Render(RenderType);
        CMCanvas.SetImage(CellMorph.GetImage());
        Graphics gr = CMCanvas.getGraphics();
        if(gr != null) {
            gr.drawImage(CellMorph.GetImage(), 0, 0, null);
        }
        
        jLabelStepCnt.setText(String.valueOf(CellMorph.StepCnt));
    }
    private void Erase() {
        CMCanvas.repaint();
    }
    
    // Updates button states, checkboxes, comboboxes etc.
    private void UpdateControls() {      
        jButtonRun.setEnabled(!timer.isRunning() && RenderType != CCellMorph.RTNeighborhood);
        jButtonStop.setEnabled(timer.isRunning() && RenderType != CCellMorph.RTNeighborhood);
        jButtonStep.setEnabled(!timer.isRunning() && RenderType != CCellMorph.RTNeighborhood);
        if (jComboBoxRender.getSelectedIndex() != RenderType)
            jComboBoxRender.setSelectedIndex(RenderType);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanelCellMorph = new javax.swing.JPanel();
        CMCanvas = new my.CellMorphs.CCellMorphCanvas();
        jPanelControls = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSliderSpeed = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jButtonStep = new javax.swing.JButton();
        jButtonRun = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jButtonReInit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxRender = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabelStepCnt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CellMorphs - Big View");
        setMinimumSize(new java.awt.Dimension(500, 300));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jPanelCellMorph.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        javax.swing.GroupLayout CMCanvasLayout = new javax.swing.GroupLayout(CMCanvas);
        CMCanvas.setLayout(CMCanvasLayout);
        CMCanvasLayout.setHorizontalGroup(
            CMCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        CMCanvasLayout.setVerticalGroup(
            CMCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCellMorphLayout = new javax.swing.GroupLayout(jPanelCellMorph);
        jPanelCellMorph.setLayout(jPanelCellMorphLayout);
        jPanelCellMorphLayout.setHorizontalGroup(
            jPanelCellMorphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCellMorphLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CMCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCellMorphLayout.setVerticalGroup(
            jPanelCellMorphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCellMorphLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CMCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelControls.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controls", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12)));
        jLabel1.setText("Speed: -");

        jSliderSpeed.setMaximum(32);
        jSliderSpeed.setValue(24);
        jSliderSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderSpeedStateChanged(evt);
            }
        });

        jLabel2.setText("+");

        jButtonStep.setText("Step");
        jButtonStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStepActionPerformed(evt);
            }
        });

        jButtonRun.setText("Run");
        jButtonRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunActionPerformed(evt);
            }
        });

        jButtonStop.setText("Stop");
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });

        jButtonReInit.setText("Reinitialize");
        jButtonReInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReInitActionPerformed(evt);
            }
        });

        jLabel3.setText("Render:");

        jComboBoxRender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cell State", "Neighbor Count", "Image", "Neighborhood Shape" }));
        jComboBoxRender.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxRenderItemStateChanged(evt);
            }
        });

        jLabel4.setText("Step:");

        jLabelStepCnt.setText("0");

        javax.swing.GroupLayout jPanelControlsLayout = new javax.swing.GroupLayout(jPanelControls);
        jPanelControls.setLayout(jPanelControlsLayout);
        jPanelControlsLayout.setHorizontalGroup(
            jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addComponent(jButtonRun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonStop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonStep))
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, 0)
                        .addComponent(jSliderSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxRender, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelControlsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelStepCnt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonReInit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelControlsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonRun, jButtonStep, jButtonStop});

        jPanelControlsLayout.setVerticalGroup(
            jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSliderSpeed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonStep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxRender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabelStepCnt)
                            .addComponent(jButtonReInit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelCellMorph, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelControls, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCellMorph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxRenderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxRenderItemStateChanged
        if (jComboBoxRender.getSelectedIndex() != -1)
            RenderType = jComboBoxRender.getSelectedIndex();
        UpdateControls();
        Erase(); // Erase the canvas
        Draw();
    }//GEN-LAST:event_jComboBoxRenderItemStateChanged

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        CellMorph.Resize(CMCanvas.getWidth(), CMCanvas.getHeight());
        Erase();
        Draw();
    }//GEN-LAST:event_formComponentResized

    private void jButtonReInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReInitActionPerformed
        CellMorph.Init();
        Erase();
        Draw();
    }//GEN-LAST:event_jButtonReInitActionPerformed

    private void jButtonStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStepActionPerformed
        CellMorph.Step();
        Draw();
    }//GEN-LAST:event_jButtonStepActionPerformed

    private void jButtonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunActionPerformed
        timer.setDelay((jSliderSpeed.getMaximum() - jSliderSpeed.getValue() + 1) * 10);
        timer.start();
        UpdateControls();
    }//GEN-LAST:event_jButtonRunActionPerformed

    private void jSliderSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderSpeedStateChanged
        timer.setDelay((jSliderSpeed.getMaximum() - jSliderSpeed.getValue() + 1) * 10);
    }//GEN-LAST:event_jSliderSpeedStateChanged

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        timer.stop();
        UpdateControls();
    }//GEN-LAST:event_jButtonStopActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private my.CellMorphs.CCellMorphCanvas CMCanvas;
    private javax.swing.JButton jButtonReInit;
    private javax.swing.JButton jButtonRun;
    private javax.swing.JButton jButtonStep;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JComboBox jComboBoxRender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelStepCnt;
    private javax.swing.JPanel jPanelCellMorph;
    private javax.swing.JPanel jPanelControls;
    private javax.swing.JSlider jSliderSpeed;
    // End of variables declaration//GEN-END:variables
    
}
